<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.11.0</Version>
    <Authors>Awadh Faghmah</Authors>
    <Company>Awadh Faghmah</Company>
    <Copyright>Copyright © 2026 Awadh Faghmah. All rights reserved.</Copyright>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts/**</DefaultItemExcludes>
    <ApplicationIcon>Assets/HamiPdf.ico</ApplicationIcon>
    <Product>HamiPdf</Product>
    <Description>عارض الحامي لملفات PDF</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <Content Include="_win*/twaindsm.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Licenses/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Resource Include="Assets/HamiPdf.ico" />
    <Resource Include="Assets/HamiPdf.png" />
    <Content Include="Forms/Web/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
    <PackageReference Include="NAPS2.Sdk" Version="1.3.0" />
    <PackageReference Include="NAPS2.Images.Wpf" Version="1.3.0" />
    <PackageReference Include="NAPS2.Sdk.Worker.Win32" Version="1.3.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>
</Project>
