using System.IO;
using HamiPdf.Forms;
using PdfSharp.Pdf;
using PdfSharp.Pdf.Advanced;
using PdfSharp.Pdf.IO;

internal static class Program
{
    private static PdfDictionary Dict(PdfItem? item) => (item is PdfReference r ? r.Value : item) as PdfDictionary ?? throw new InvalidDataException("Expected PDF dictionary");
    private static void Require(bool value,string message){if(!value)throw new Exception(message);}
    [STAThread]
    private static void Main(string[] args)
    {
        // Optional real-world fixture, generated by the browser checks, remains local to the user.
        if(args.Length==2){File.WriteAllBytes(args[1],FormAppearance.Prepare(File.ReadAllBytes(args[0])));Console.WriteLine("PASS: supplied form prepared and verified.");return;}
        byte[] source;
        using(var doc=new PdfDocument())
        {
            var page=doc.AddPage();
            var form=new PdfDictionary(doc);doc.Internals.AddObject(form);
            form.Elements.SetBoolean("/NeedAppearances",true);
            var fields=new PdfArray(doc);form.Elements["/Fields"]=fields;
            doc.Internals.Catalog.Elements["/AcroForm"]=form.Reference!;
            var annotations=new PdfArray(doc);page.Elements["/Annots"]=annotations;
            for(int i=0;i<3;i++)
            {
                var field=new PdfDictionary(doc);doc.Internals.AddObject(field);
                field.Elements.SetString("/T","Text"+i);field.Elements.SetName("/FT","/Tx");
                field.Elements.SetString("/V",i==0?"عوض عبيد 123":i==1?"Second line\nسطر ثان":"");
                field.Elements.SetString("/DA","/Helv 12 Tf 0 g");field.Elements.SetInteger("/Q",2);
                if(i==1)field.Elements.SetInteger("/Ff",4096);
                var widget=new PdfDictionary(doc);doc.Internals.AddObject(widget);
                widget.Elements.SetName("/Type","/Annot");widget.Elements.SetName("/Subtype","/Widget");
                widget.Elements["/Rect"]=new PdfRectangle(new PdfSharp.Drawing.XRect(30,100+i*70,220,60));
                widget.Elements["/Parent"]=field.Reference!;widget.Elements["/P"]=page.Reference!;
                if(i==2){var mk=new PdfDictionary(doc);mk.Elements.SetInteger("/R",90);widget.Elements["/MK"]=mk;}
                var kids=new PdfArray(doc);kids.Elements.Add(widget.Reference!);field.Elements["/Kids"]=kids;
                fields.Elements.Add(field.Reference!);annotations.Elements.Add(widget.Reference!);
            }
            using var ms=new MemoryStream();doc.Save(ms,false);source=ms.ToArray();
        }
        var prepared=FormAppearance.Prepare(source);
        using(var ms=new MemoryStream(prepared,false))using(var check=PdfReader.Open(ms,PdfDocumentOpenMode.Import))
        {
            var form=Dict(check.Internals.Catalog.Elements["/AcroForm"]);
            Require(!form.Elements.GetBoolean("/NeedAppearances"),"Appearance regeneration must be complete");
            var fields=(PdfArray)form.Elements["/Fields"]!;
            Require(fields.Elements.Count==3,"All canonical fields must survive");
            Require(Dict(fields.Elements[0]).Elements.GetString("/V")=="عوض عبيد 123","Arabic /V must survive");
            foreach(var item in ((PdfArray)check.Pages[0].Elements["/Annots"]!).Elements)
            {
                var widget=Dict(item);var ap=Dict(Dict(widget.Elements["/AP"]).Elements["/N"]);
                Require(ap.Stream!=null && ap.Stream.Value.Length>0,"Every text widget requires an appearance stream");
                Require(widget.Elements.ContainsKey("/Parent"),"Widgets must retain canonical parent links");
                var image=Dict(Dict(Dict(ap.Elements["/Resources"]).Elements["/XObject"]).Elements["/Im"]);
                Require(image.Elements.GetInteger("/Width")>0,"Text appearance must include a raster image");
            }
        }
        var again=FormAppearance.Prepare(prepared);Require(again.SequenceEqual(prepared),"Prepared appearance must not be rewritten unnecessarily");
        string dir=Path.Combine(Path.GetTempPath(),"HamiPdfForms-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);
        try{var path=Path.Combine(dir,"معبأ.pdf");AtomicPdfSave.Write(path,source);AtomicPdfSave.Write(path,prepared);Require(File.ReadAllBytes(path+".bak").SequenceEqual(source),"Backup must preserve previous bytes");Require(File.ReadAllBytes(path).SequenceEqual(prepared),"New bytes must be committed");}
        finally{Directory.Delete(dir,true);}
        Console.WriteLine("PASS: Arabic form values, parent links, appearance streams, idempotence and atomic backup.");
    }
}
