const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
if(!process.argv[2]) throw Error('Usage: node run.cjs /path/to/55.pdf');
const out=path.resolve('form-browser-results');fs.mkdirSync(out,{recursive:true});
(async()=>{
const http=require('http');
const server=http.createServer((req,res)=>{const file=path.join(__dirname,'../../Forms/Web',decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8891,'127.0.0.1',r));
const browser=await chromium.launch({...(process.env.HAMIPDF_CHROMIUM ? {executablePath:process.env.HAMIPDF_CHROMIUM} : {}),headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1120,height:800}});page.on('pageerror',e=>console.log('PAGEERROR',e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(m.type(),m.text())});
await page.addInitScript(()=>{window.received=[];window.chrome={webview:{postMessage:m=>window.received.push(m),addEventListener:(type,fn)=>window.hostReply=fn}}});
await page.goto('http://127.0.0.1:8891/index.html');await page.waitForFunction(()=>window.hami);
await page.evaluate(b=>window.hami.open(b),fs.readFileSync(process.argv[2]).toString('base64'));
await page.waitForTimeout(2500);console.log('STATUS',await page.locator('#status').textContent());console.log('INPUTS',await page.locator('input').count());
await page.screenshot({path:path.join(out,'ui-before.png')});
await page.locator('input[type=text]').first().fill('عوض عبيد 123');await page.locator('input[type=checkbox]').first().check();
await page.locator('#save').click();await page.waitForTimeout(2500);console.log('SAVE STATUS',await page.locator('#status').textContent());
const msg=await page.evaluate(()=>window.received.find(x=>x.type==='save'));if(!msg)throw Error('Save did not produce data');fs.writeFileSync(path.join(out,'browser-saved.pdf'),Buffer.from(msg.data,'base64'));
await page.evaluate(()=>window.hostReply({data:{type:'saved',ok:false,message:'cancelled'}}));
if(await page.locator('#save').isDisabled())throw Error('Cancel left the editor locked');
await page.locator('input[type=text]').first().fill('الحامي 456');
await page.locator('input[type=checkbox]').first().uncheck();
await page.evaluate(()=>window.received=[]);await page.locator('#save').click();
await page.waitForFunction(()=>window.received.some(x=>x.type==='save'));
const second=await page.evaluate(()=>window.received.find(x=>x.type==='save'));
fs.writeFileSync(path.join(out,'browser-second-save.pdf'),Buffer.from(second.data,'base64'));
await page.evaluate(()=>window.hostReply({data:{type:'saved',ok:true,message:'saved'}}));
if(await page.locator('#save').isDisabled())throw Error('Success left editor locked');
await page.screenshot({path:path.join(out,'ui-filled.png')});
const reopen=await browser.newPage();await reopen.goto('http://127.0.0.1:8891/index.html');await reopen.waitForFunction(()=>window.hami);await reopen.evaluate(b=>window.hami.open(b),second.data);await reopen.waitForSelector('input[type=text]');
if(await reopen.locator('input[type=text]').first().inputValue()!=='الحامي 456')throw Error('Arabic value did not reopen');
if(await reopen.locator('input[type=checkbox]').first().isChecked())throw Error('Unchecked state did not reopen');
if(await reopen.locator('input').count()!==70)throw Error('Fields were lost');
console.log('PASS: 70 fields, Arabic input, checkbox on/off, save cancellation, repeated saves and reopening.');
await browser.close();server.close();
})();
